#!/usr/bin/env python3
import os
import sys
from openai import AzureOpenAI

env_use_identity = os.getenv("AZURE_OPENAI_USE_IDENTITY", "false")
use_identity = env_use_identity == 'true' or env_use_identity == '1' or env_use_identity == 'on'

if use_identity:
  from azure.identity import DefaultAzureCredential, get_bearer_token_provider
  token_provider = get_bearer_token_provider(
    DefaultAzureCredential(), "https://cognitiveservices.azure.com/.default"
  )
  client = AzureOpenAI(
    azure_ad_token_provider = token_provider,
    azure_endpoint = os.getenv("AZURE_OPENAI_ENDPOINT"),
    api_version = "2024-02-15-preview"
  )
else:
  client = AzureOpenAI(
    api_key = os.getenv("AZURE_OPENAI_API_KEY"),
    azure_endpoint = os.getenv("AZURE_OPENAI_ENDPOINT"),
    api_version = "2024-02-15-preview"
  )

response = client.chat.completions.create(
    model=os.getenv("AZURE_OPENAI_MODEL"),
    temperature=0.0,
    messages=[
              {"role": "system", "content": "You are a tool designed to help users run commands in the terminal. Please provide the commands or script output in plain text without any markup. Avoid using backticks (`) around the command or a full stop (.) at the end of the line. Do not provide any explanations."},
              {"role": "user", "content": " ".join(sys.argv[1:])},
    ],
)

print(response.choices[0].message.content)
